















LOCX = 0
LOCY = 1
LOCZ = 2


copy_buffer = {} 

joint_data = {
    "mPelvis": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mSpine1": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mSpine2": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mSpine3": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mSpine4": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTorso": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mChest": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mNeck": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHead": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mSkull": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mEyeRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mEyeLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceRoot": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceJaw": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceChin": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceNoseCenter": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceTeethUpper": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceTeethLower": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceTongueBase": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceTongueTip": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceJawShaper": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceForeheadCenter": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceNoseBase": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipUpperCenter": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipLowerCenter": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceNoseBridge": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyeAltLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyeAltRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceForeheadLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceForeheadRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyebrowOuterLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyebrowOuterRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyebrowCenterLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyebrowCenterRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyebrowInnerLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyebrowInnerRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyeLidUpperLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyeLidUpperRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyeLidLowerLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyeLidLowerRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEar1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEar1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEar2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEar2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceNoseLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceNoseRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceCheekUpperLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceCheekUpperRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceCheekLowerLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceCheekLowerRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipLowerLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipLowerRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipUpperLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipUpperRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipCornerLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceLipCornerRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyecornerInnerLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFaceEyecornerInnerRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mCollarLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mCollarRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['-', '-', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mShoulderLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', '',],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', '',],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', '',],
    },
    "mShoulderRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['-', '-', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['-', '-', ''],
    },
    "mElbowLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mElbowRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['-', '-', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['-', '-', ''],
    },
    "mWristLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWristRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['-', '-', ''],
        "loc_offset_angle": [LOCY, LOCX, LOCZ],
        "loc_offset_inverted": ['-', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['-', '-', ''],
    },
    "mHandMiddle1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandMiddle2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandMiddle3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandMiddle1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandMiddle2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandMiddle3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandIndex1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandIndex2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandIndex3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandIndex1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandIndex2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandIndex3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandRing1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandRing2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandRing3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandRing1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandRing2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandRing3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandPinky1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandPinky2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandPinky3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandPinky1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandPinky2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandPinky3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandThumb1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandThumb2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandThumb3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandThumb1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandThumb2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHandThumb3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWingsRoot": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing4Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing4Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing4FanLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mWing4FanRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHipLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHipRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mKneeLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mKneeRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mAnkleLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mAnkleRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFootLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mFootRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mToeLeft": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mToeRight": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTail1": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTail2": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTail3": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTail4": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTail5": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mTail6": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mGroin": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimbsRoot": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb1Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb2Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb3Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb4Left": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb1Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb2Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb3Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "mHindLimb4Right": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "NECK": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "BELLY": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "PELVIS": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "CHEST": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "LEFT_PEC": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "RIGHT_PEC": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "HEAD": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "BUTT": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "UPPER_BACK": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "LOWER_BACK": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_CLAVICLE": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_CLAVICLE": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_UPPER_ARM": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_UPPER_ARM": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_LOWER_ARM": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_LOWER_ARM": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "LEFT_HANDLE": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "RIGHT_HANDLE": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_UPPER_LEG": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_UPPER_LEG": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_LOWER_LEG": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_LOWER_LEG": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_HAND": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_HAND": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "L_FOOT": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
    "R_FOOT": {
        "copy": "",
        "locked": False,
        "loc_axis_angle": [LOCX, LOCY, LOCZ],
        "loc_axis_inverted": ['', '', ''],
        "loc_offset_angle": [LOCX, LOCY, LOCZ],
        "loc_offset_inverted": ['', '', ''],
        "rot_axis_angle": [LOCX, LOCY, LOCZ],
        "rot_axis_inverted": ['', '', ''],
    },
}
