














joint_data_header ="""
# Auto-generated by Bento Buddy

LOCX = 0
LOCY = 1
LOCZ = 2

joint_data = {"""



joint_data_content ="""
    "%BONE": {
        "copy": copy_data,
        "locked": locked_data,
        "loc_axis_angle": [loc_axis_angle_data],
        "loc_axis_inverted": [loc_axis_inverted_data],
        "loc_offset_angle": [loc_offset_angle_data],
        "loc_offset_inverted": [loc_offset_inverted_data],
        "rot_axis_angle": [rot_axis_angle_data],
        "rot_axis_inverted": [rot_axis_inverted_data],
    },"""

joint_data_footer ="""
}
"""












