bone_map = {
    "mPelvis": "Pelvis",
    "PELVIS": "PELVIS",
    "BUTT": "BUTT",
    "mSpine1": "Spine1",
    "mSpine2": "Spine2",
    "mTorso": "Torso",
    "BELLY": "BELLY",
    "LEFT_HANDLE": "LEFT_HANDLE",
    "RIGHT_HANDLE": "RIGHT_HANDLE",
    "LOWER_BACK": "LOWER_BACK",
    "mSpine3": "Spine3",
    "mSpine4": "Spine4",
    "mChest": "Chest",
    "CHEST": "CHEST",
    "LEFT_PEC": "LEFT_PEC",
    "RIGHT_PEC": "RIGHT_PEC",
    "UPPER_BACK": "UPPER_BACK",
    "mNeck": "Neck",
    "NECK": "NECK",
    "mHead": "Head",
    "HEAD": "HEAD",
    "mSkull": "Skull",
    "mEyeRight": "EyeRight",
    "aRight Eyeball": "Right Eyeball",
    "mEyeLeft": "EyeLeft",
    "aLeft Eyeball": "Left Eyeball",
    "mFaceRoot": "FaceRoot",
    "mFaceEyeAltRight": "FaceEyeAltRight",
    "aAlt Right Eye": "Alt Right Eye",
    "mFaceEyeAltLeft": "FaceEyeAltLeft",
    "aAlt Left Eye": "Alt Left Eye",
    "mFaceForeheadLeft": "FaceForeheadLeft",
    "mFaceForeheadRight": "FaceForeheadRight",
    "mFaceEyebrowOuterLeft": "FaceEyebrowOuterLeft",
    "mFaceEyebrowCenterLeft": "FaceEyebrowCenterLeft",
    "mFaceEyebrowInnerLeft": "FaceEyebrowInnerLeft",
    "mFaceEyebrowOuterRight": "FaceEyebrowOuterRight",
    "mFaceEyebrowCenterRight": "FaceEyebrowCenterRight",
    "mFaceEyebrowInnerRight": "FaceEyebrowInnerRight",
    "mFaceEyeLidUpperLeft": "FaceEyeLidUpperLeft",
    "mFaceEyeLidLowerLeft": "FaceEyeLidLowerLeft",
    "mFaceEyeLidUpperRight": "FaceEyeLidUpperRight",
    "mFaceEyeLidLowerRight": "FaceEyeLidLowerRight",
    "mFaceEar1Left": "FaceEar1Left",
    "mFaceEar2Left": "FaceEar2Left",
    "aAlt Left Ear": "Alt Left Ear",
    "mFaceEar1Right": "FaceEar1Right",
    "mFaceEar2Right": "FaceEar2Right",
    "aAlt Right Ear": "Alt Right Ear",
    "mFaceNoseLeft": "FaceNoseLeft",
    "mFaceNoseCenter": "FaceNoseCenter",
    "mFaceNoseRight": "FaceNoseRight",
    "mFaceCheekLowerLeft": "FaceCheekLowerLeft",
    "mFaceCheekUpperLeft": "FaceCheekUpperLeft",
    "mFaceCheekLowerRight": "FaceCheekLowerRight",
    "mFaceCheekUpperRight": "FaceCheekUpperRight",
    "mFaceJaw": "FaceJaw",
    "mFaceChin": "FaceChin",
    "mFaceTeethLower": "FaceTeethLower",
    "mFaceLipLowerLeft": "FaceLipLowerLeft",
    "mFaceLipLowerRight": "FaceLipLowerRight",
    "mFaceLipLowerCenter": "FaceLipLowerCenter",
    "mFaceTongueBase": "FaceTongueBase",
    "mFaceTongueTip": "FaceTongueTip",
    "aTongue": "Tongue",
    "aJaw": "Jaw",
    "mFaceJawShaper": "FaceJawShaper",
    "mFaceForeheadCenter": "FaceForeheadCenter",
    "mFaceNoseBase": "FaceNoseBase",
    "mFaceTeethUpper": "FaceTeethUpper",
    "mFaceLipUpperLeft": "FaceLipUpperLeft",
    "mFaceLipUpperRight": "FaceLipUpperRight",
    "mFaceLipCornerLeft": "FaceLipCornerLeft",
    "mFaceLipCornerRight": "FaceLipCornerRight",
    "mFaceLipUpperCenter": "FaceLipUpperCenter",
    "mFaceEyecornerInnerLeft": "FaceEyecornerInnerLeft",
    "mFaceEyecornerInnerRight": "FaceEyecornerInnerRight",
    "mFaceNoseBridge": "FaceNoseBridge",
    "aSkull": "Skull",
    "aMouth": "Mouth",
    "aChin": "Chin",
    "aLeft Ear": "Left Ear",
    "aRight Ear": "Right Ear",
    "aNose": "Nose",
    "aNeck": "Neck",
    "mCollarLeft": "CollarLeft",
    "L_CLAVICLE": "L_CLAVICLE",
    "mShoulderLeft": "ShoulderLeft",
    "L_UPPER_ARM": "L_UPPER_ARM",
    "mElbowLeft": "ElbowLeft",
    "L_LOWER_ARM": "L_LOWER_ARM",
    "mWristLeft": "WristLeft",
    "L_HAND": "L_HAND",
    "mHandMiddle1Left": "HandMiddle1Left",
    "mHandMiddle2Left": "HandMiddle2Left",
    "mHandMiddle3Left": "HandMiddle3Left",
    "mHandIndex1Left": "HandIndex1Left",
    "mHandIndex2Left": "HandIndex2Left",
    "mHandIndex3Left": "HandIndex3Left",
    "mHandRing1Left": "HandRing1Left",
    "mHandRing2Left": "HandRing2Left",
    "mHandRing3Left": "HandRing3Left",
    "aLeft Ring Finger": "Left Ring Finger",
    "mHandPinky1Left": "HandPinky1Left",
    "mHandPinky2Left": "HandPinky2Left",
    "mHandPinky3Left": "HandPinky3Left",
    "mHandThumb1Left": "HandThumb1Left",
    "mHandThumb2Left": "HandThumb2Left",
    "mHandThumb3Left": "HandThumb3Left",
    "aLeft Hand": "Left Hand",
    "aL Forearm": "L Forearm",
    "aL Upper Arm": "L Upper Arm",
    "aLeft Shoulder": "Left Shoulder",
    "mCollarRight": "CollarRight",
    "R_CLAVICLE": "R_CLAVICLE",
    "mShoulderRight": "ShoulderRight",
    "R_UPPER_ARM": "R_UPPER_ARM",
    "mElbowRight": "ElbowRight",
    "R_LOWER_ARM": "R_LOWER_ARM",
    "mWristRight": "WristRight",
    "R_HAND": "R_HAND",
    "mHandMiddle1Right": "HandMiddle1Right",
    "mHandMiddle2Right": "HandMiddle2Right",
    "mHandMiddle3Right": "HandMiddle3Right",
    "mHandIndex1Right": "HandIndex1Right",
    "mHandIndex2Right": "HandIndex2Right",
    "mHandIndex3Right": "HandIndex3Right",
    "mHandRing1Right": "HandRing1Right",
    "mHandRing2Right": "HandRing2Right",
    "mHandRing3Right": "HandRing3Right",
    "aRight Ring Finger": "Right Ring Finger",
    "mHandPinky1Right": "HandPinky1Right",
    "mHandPinky2Right": "HandPinky2Right",
    "mHandPinky3Right": "HandPinky3Right",
    "mHandThumb1Right": "HandThumb1Right",
    "mHandThumb2Right": "HandThumb2Right",
    "mHandThumb3Right": "HandThumb3Right",
    "aRight Hand": "Right Hand",
    "aR Forearm": "R Forearm",
    "aR Upper Arm": "R Upper Arm",
    "aRight Shoulder": "Right Shoulder",
    "mWingsRoot": "WingsRoot",
    "mWing1Left": "Wing1Left",
    "mWing2Left": "Wing2Left",
    "mWing3Left": "Wing3Left",
    "mWing4Left": "Wing4Left",
    "aLeft Wing": "Left Wing",
    "mWing4FanLeft": "Wing4FanLeft",
    "mWing1Right": "Wing1Right",
    "mWing2Right": "Wing2Right",
    "mWing3Right": "Wing3Right",
    "mWing4Right": "Wing4Right",
    "aRight Wing": "Right Wing",
    "mWing4FanRight": "Wing4FanRight",
    "aChest": "Chest",
    "aSpine": "Spine",
    "aLeft Pec": "Left Pec",
    "aRight Pec": "Right Pec",
    "mHipRight": "HipRight",
    "R_UPPER_LEG": "R_UPPER_LEG",
    "mKneeRight": "KneeRight",
    "R_LOWER_LEG": "R_LOWER_LEG",
    "mAnkleRight": "AnkleRight",
    "R_FOOT": "R_FOOT",
    "mFootRight": "FootRight",
    "mToeRight": "ToeRight",
    "aRight Foot": "Right Foot",
    "aR Lower Leg": "R Lower Leg",
    "aRight Hip": "Right Hip",
    "aR Upper Leg": "R Upper Leg",
    "mHipLeft": "HipLeft",
    "L_UPPER_LEG": "L_UPPER_LEG",
    "mKneeLeft": "KneeLeft",
    "L_LOWER_LEG": "L_LOWER_LEG",
    "mAnkleLeft": "AnkleLeft",
    "L_FOOT": "L_FOOT",
    "mFootLeft": "FootLeft",
    "mToeLeft": "ToeLeft",
    "aLeft Foot": "Left Foot",
    "aL Lower Leg": "L Lower Leg",
    "aLeft Hip": "Left Hip",
    "aL Upper Leg": "L Upper Leg",
    "mTail1": "Tail1",
    "mTail2": "Tail2",
    "mTail3": "Tail3",
    "mTail4": "Tail4",
    "mTail5": "Tail5",
    "mTail6": "Tail6",
    "aTail Tip": "Tail Tip",
    "aTail Base": "Tail Base",
    "mGroin": "Groin",
    "aGroin": "Groin",
    "mHindLimbsRoot": "HindLimbsRoot",
    "mHindLimb1Left": "HindLimb1Left",
    "mHindLimb2Left": "HindLimb2Left",
    "mHindLimb3Left": "HindLimb3Left",
    "mHindLimb4Left": "HindLimb4Left",
    "aLeft Hind Foot": "Left Hind Foot",
    "mHindLimb1Right": "HindLimb1Right",
    "mHindLimb2Right": "HindLimb2Right",
    "mHindLimb3Right": "HindLimb3Right",
    "mHindLimb4Right": "HindLimb4Right",
    "aRight Hind Foot": "Right Hind Foot",
    "aPelvis": "Pelvis",
    "aStomach": "Stomach",
    "Torso": "mTorso",
    "Spine3": "mSpine3",
    "Spine4": "mSpine4",
    "Chest": "mChest",
    "Neck": "mNeck",
    "Head": "mHead",
    "Skull": "mSkull",
    "EyeRight": "mEyeRight",
    "EyeLeft": "mEyeLeft",
    "FaceRoot": "mFaceRoot",
    "FaceEyeAltRight": "mFaceEyeAltRight",
    "FaceEyeAltLeft": "mFaceEyeAltLeft",
    "FaceForeheadLeft": "mFaceForeheadLeft",
    "FaceForeheadRight": "mFaceForeheadRight",
    "FaceEyebrowOuterLeft": "mFaceEyebrowOuterLeft",
    "FaceEyebrowCenterLeft": "mFaceEyebrowCenterLeft",
    "FaceEyebrowInnerLeft": "mFaceEyebrowInnerLeft",
    "FaceEyebrowOuterRight": "mFaceEyebrowOuterRight",
    "FaceEyebrowCenterRight": "mFaceEyebrowCenterRight",
    "FaceEyebrowInnerRight": "mFaceEyebrowInnerRight",
    "FaceEyeLidUpperLeft": "mFaceEyeLidUpperLeft",
    "FaceEyeLidLowerLeft": "mFaceEyeLidLowerLeft",
    "FaceEyeLidUpperRight": "mFaceEyeLidUpperRight",
    "FaceEyeLidLowerRight": "mFaceEyeLidLowerRight",
    "FaceEar1Left": "mFaceEar1Left",
    "FaceEar2Left": "mFaceEar2Left",
    "FaceEar1Right": "mFaceEar1Right",
    "FaceEar2Right": "mFaceEar2Right",
    "FaceNoseLeft": "mFaceNoseLeft",
    "FaceNoseCenter": "mFaceNoseCenter",
    "FaceNoseRight": "mFaceNoseRight",
    "FaceCheekLowerLeft": "mFaceCheekLowerLeft",
    "FaceCheekUpperLeft": "mFaceCheekUpperLeft",
    "FaceCheekLowerRight": "mFaceCheekLowerRight",
    "FaceCheekUpperRight": "mFaceCheekUpperRight",
    "FaceJaw": "mFaceJaw",
    "FaceChin": "mFaceChin",
    "FaceTeethLower": "mFaceTeethLower",
    "FaceLipLowerLeft": "mFaceLipLowerLeft",
    "FaceLipLowerRight": "mFaceLipLowerRight",
    "FaceLipLowerCenter": "mFaceLipLowerCenter",
    "FaceTongueBase": "mFaceTongueBase",
    "FaceTongueTip": "mFaceTongueTip",
    "FaceJawShaper": "mFaceJawShaper",
    "FaceForeheadCenter": "mFaceForeheadCenter",
    "FaceNoseBase": "mFaceNoseBase",
    "FaceTeethUpper": "mFaceTeethUpper",
    "FaceLipUpperLeft": "mFaceLipUpperLeft",
    "FaceLipUpperRight": "mFaceLipUpperRight",
    "FaceLipCornerLeft": "mFaceLipCornerLeft",
    "FaceLipCornerRight": "mFaceLipCornerRight",
    "FaceLipUpperCenter": "mFaceLipUpperCenter",
    "FaceEyecornerInnerLeft": "mFaceEyecornerInnerLeft",
    "FaceEyecornerInnerRight": "mFaceEyecornerInnerRight",
    "FaceNoseBridge": "mFaceNoseBridge",
    "WingsRoot": "mWingsRoot",
    "Wing1Left": "mWing1Left",
    "Wing2Left": "mWing2Left",
    "Wing3Left": "mWing3Left",
    "Wing4Left": "mWing4Left",
    "Wing4FanLeft": "mWing4FanLeft",
    "Wing1Right": "mWing1Right",
    "Wing2Right": "mWing2Right",
    "Wing3Right": "mWing3Right",
    "Wing4Right": "mWing4Right",
    "Wing4FanRight": "mWing4FanRight",
    "CollarLeft": "mCollarLeft",
    "ShoulderLeft": "mShoulderLeft",
    "ElbowLeft": "mElbowLeft",
    "WristLeft": "mWristLeft",
    "HandIndex1Left": "mHandIndex1Left",
    "HandIndex2Left": "mHandIndex2Left",
    "HandIndex3Left": "mHandIndex3Left",
    "HandMiddle1Left": "mHandMiddle1Left",
    "HandMiddle2Left": "mHandMiddle2Left",
    "HandMiddle3Left": "mHandMiddle3Left",
    "HandRing1Left": "mHandRing1Left",
    "HandRing2Left": "mHandRing2Left",
    "HandRing3Left": "mHandRing3Left",
    "HandPinky1Left": "mHandPinky1Left",
    "HandPinky2Left": "mHandPinky2Left",
    "HandPinky3Left": "mHandPinky3Left",
    "HandThumb1Left": "mHandThumb1Left",
    "HandThumb2Left": "mHandThumb2Left",
    "HandThumb3Left": "mHandThumb3Left",
    "CollarRight": "mCollarRight",
    "ShoulderRight": "mShoulderRight",
    "ElbowRight": "mElbowRight",
    "WristRight": "mWristRight",
    "HandIndex1Right": "mHandIndex1Right",
    "HandIndex2Right": "mHandIndex2Right",
    "HandIndex3Right": "mHandIndex3Right",
    "HandMiddle1Right": "mHandMiddle1Right",
    "HandMiddle2Right": "mHandMiddle2Right",
    "HandMiddle3Right": "mHandMiddle3Right",
    "HandRing1Right": "mHandRing1Right",
    "HandRing2Right": "mHandRing2Right",
    "HandRing3Right": "mHandRing3Right",
    "HandPinky1Right": "mHandPinky1Right",
    "HandPinky2Right": "mHandPinky2Right",
    "HandPinky3Right": "mHandPinky3Right",
    "HandThumb1Right": "mHandThumb1Right",
    "HandThumb2Right": "mHandThumb2Right",
    "HandThumb3Right": "mHandThumb3Right",
    "Pelvis": "mPelvis",
    "Spine1": "mSpine1",
    "Spine2": "mSpine2",
    "Tail1": "mTail1",
    "Tail2": "mTail2",
    "Tail3": "mTail3",
    "Tail4": "mTail4",
    "Tail5": "mTail5",
    "Tail6": "mTail6",
    "Groin": "mGroin",
    "HindLimbsRoot": "mHindLimbsRoot",
    "HindLimb1Left": "mHindLimb1Left",
    "HindLimb2Left": "mHindLimb2Left",
    "HindLimb3Left": "mHindLimb3Left",
    "HindLimb4Left": "mHindLimb4Left",
    "HindLimb1Right": "mHindLimb1Right",
    "HindLimb2Right": "mHindLimb2Right",
    "HindLimb3Right": "mHindLimb3Right",
    "HindLimb4Right": "mHindLimb4Right",
    "HipLeft": "mHipLeft",
    "KneeLeft": "mKneeLeft",
    "AnkleLeft": "mAnkleLeft",
    "FootLeft": "mFootLeft",
    "ToeLeft": "mToeLeft",
    "HipRight": "mHipRight",
    "KneeRight": "mKneeRight",
    "AnkleRight": "mAnkleRight",
    "FootRight": "mFootRight",
    "ToeRight": "mToeRight",
    "aAvatar Center": "Avatar Center",
    'PelvisInv': 'PelvisInv',
    'COG': 'mPelvis',
    'Origin': 'Origin',
    'Tinker': 'Tinker',

}





