bone_map = {
    'mPelvis': "mPelvis",
    'PELVIS': "PELVIS",
    'BUTT': "BUTT",
    'mSpine1': "mSpine1",
    'mSpine2': "mSpine2",
    'mTorso': "mTorso",
    'BELLY': "BELLY",
    'LEFT_HANDLE': "LEFT_HANDLE",
    'RIGHT_HANDLE': "RIGHT_HANDLE",
    'LOWER_BACK': "LOWER_BACK",
    'mSpine3': "mSpine3",
    'mSpine4': "mSpine4",
    'mChest': "mChest",
    'CHEST': "CHEST",
    'LEFT_PEC': "LEFT_PEC",
    'RIGHT_PEC': "RIGHT_PEC",
    'UPPER_BACK': "UPPER_BACK",
    'mNeck': "mNeck",
    'NECK': "NECK",
    'mHead': "mHead",
    'HEAD': "HEAD",
    'mSkull': "mSkull",
    'mEyeRight': "mEyeRight",
    'aRight Eyeball': "Right Eyeball",
    'mEyeLeft': "mEyeLeft",
    'aLeft Eyeball': "Left Eyeball",
    'mFaceRoot': "mFaceRoot",
    'mFaceEyeAltRight': "mFaceEyeAltRight",
    'aAlt Right Eye': "Alt Right Eye",
    'mFaceEyeAltLeft': "mFaceEyeAltLeft",
    'aAlt Left Eye': "Alt Left Eye",
    'mFaceForeheadLeft': "mFaceForeheadLeft",
    'mFaceForeheadRight': "mFaceForeheadRight",
    'mFaceEyebrowOuterLeft': "mFaceEyebrowOuterLeft",
    'mFaceEyebrowCenterLeft': "mFaceEyebrowCenterLeft",
    'mFaceEyebrowInnerLeft': "mFaceEyebrowInnerLeft",
    'mFaceEyebrowOuterRight': "mFaceEyebrowOuterRight",
    'mFaceEyebrowCenterRight': "mFaceEyebrowCenterRight",
    'mFaceEyebrowInnerRight': "mFaceEyebrowInnerRight",
    'mFaceEyeLidUpperLeft': "mFaceEyeLidUpperLeft",
    'mFaceEyeLidLowerLeft': "mFaceEyeLidLowerLeft",
    'mFaceEyeLidUpperRight': "mFaceEyeLidUpperRight",
    'mFaceEyeLidLowerRight': "mFaceEyeLidLowerRight",
    'mFaceEar1Left': "mFaceEar1Left",
    'mFaceEar2Left': "mFaceEar2Left",
    'aAlt Left Ear': "Alt Left Ear",
    'mFaceEar1Right': "mFaceEar1Right",
    'mFaceEar2Right': "mFaceEar2Right",
    'aAlt Right Ear': "Alt Right Ear",
    'mFaceNoseLeft': "mFaceNoseLeft",
    'mFaceNoseCenter': "mFaceNoseCenter",
    'mFaceNoseRight': "mFaceNoseRight",
    'mFaceCheekLowerLeft': "mFaceCheekLowerLeft",
    'mFaceCheekUpperLeft': "mFaceCheekUpperLeft",
    'mFaceCheekLowerRight': "mFaceCheekLowerRight",
    'mFaceCheekUpperRight': "mFaceCheekUpperRight",
    'mFaceJaw': "mFaceJaw",
    'mFaceChin': "mFaceChin",
    'mFaceTeethLower': "mFaceTeethLower",
    'mFaceLipLowerLeft': "mFaceLipLowerLeft",
    'mFaceLipLowerRight': "mFaceLipLowerRight",
    'mFaceLipLowerCenter': "mFaceLipLowerCenter",
    'mFaceTongueBase': "mFaceTongueBase",
    'mFaceTongueTip': "mFaceTongueTip",
    'aTongue': "Tongue",
    'aJaw': "Jaw",
    'mFaceJawShaper': "mFaceJawShaper",
    'mFaceForeheadCenter': "mFaceForeheadCenter",
    'mFaceNoseBase': "mFaceNoseBase",
    'mFaceTeethUpper': "mFaceTeethUpper",
    'mFaceLipUpperLeft': "mFaceLipUpperLeft",
    'mFaceLipUpperRight': "mFaceLipUpperRight",
    'mFaceLipCornerLeft': "mFaceLipCornerLeft",
    'mFaceLipCornerRight': "mFaceLipCornerRight",
    'mFaceLipUpperCenter': "mFaceLipUpperCenter",
    'mFaceEyecornerInnerLeft': "mFaceEyecornerInnerLeft",
    'mFaceEyecornerInnerRight': "mFaceEyecornerInnerRight",
    'mFaceNoseBridge': "mFaceNoseBridge",
    'aSkull': "Skull",
    'aMouth': "Mouth",
    'aChin': "Chin",
    'aLeft Ear': "Left Ear",
    'aRight Ear': "Right Ear",
    'aNose': "Nose",
    'aNeck': "Neck",
    'mCollarLeft': "mCollarLeft",
    'L_CLAVICLE': "L_CLAVICLE",
    'mShoulderLeft': "mShoulderLeft",
    'L_UPPER_ARM': "L_UPPER_ARM",
    'mElbowLeft': "mElbowLeft",
    'L_LOWER_ARM': "L_LOWER_ARM",
    'mWristLeft': "mWristLeft",
    'L_HAND': "L_HAND",
    'mHandMiddle1Left': "mHandMiddle1Left",
    'mHandMiddle2Left': "mHandMiddle2Left",
    'mHandMiddle3Left': "mHandMiddle3Left",
    'mHandIndex1Left': "mHandIndex1Left",
    'mHandIndex2Left': "mHandIndex2Left",
    'mHandIndex3Left': "mHandIndex3Left",
    'mHandRing1Left': "mHandRing1Left",
    'mHandRing2Left': "mHandRing2Left",
    'mHandRing3Left': "mHandRing3Left",
    'aLeft Ring Finger': "Left Ring Finger",
    'mHandPinky1Left': "mHandPinky1Left",
    'mHandPinky2Left': "mHandPinky2Left",
    'mHandPinky3Left': "mHandPinky3Left",
    'mHandThumb1Left': "mHandThumb1Left",
    'mHandThumb2Left': "mHandThumb2Left",
    'mHandThumb3Left': "mHandThumb3Left",
    'aLeft Hand': "Left Hand",
    'aL Forearm': "L Forearm",
    'aL Upper Arm': "L Upper Arm",
    'aLeft Shoulder': "Left Shoulder",
    'mCollarRight': "mCollarRight",
    'R_CLAVICLE': "R_CLAVICLE",
    'mShoulderRight': "mShoulderRight",
    'R_UPPER_ARM': "R_UPPER_ARM",
    'mElbowRight': "mElbowRight",
    'R_LOWER_ARM': "R_LOWER_ARM",
    'mWristRight': "mWristRight",
    'R_HAND': "R_HAND",
    'mHandMiddle1Right': "mHandMiddle1Right",
    'mHandMiddle2Right': "mHandMiddle2Right",
    'mHandMiddle3Right': "mHandMiddle3Right",
    'mHandIndex1Right': "mHandIndex1Right",
    'mHandIndex2Right': "mHandIndex2Right",
    'mHandIndex3Right': "mHandIndex3Right",
    'mHandRing1Right': "mHandRing1Right",
    'mHandRing2Right': "mHandRing2Right",
    'mHandRing3Right': "mHandRing3Right",
    'aRight Ring Finger': "Right Ring Finger",
    'mHandPinky1Right': "mHandPinky1Right",
    'mHandPinky2Right': "mHandPinky2Right",
    'mHandPinky3Right': "mHandPinky3Right",
    'mHandThumb1Right': "mHandThumb1Right",
    'mHandThumb2Right': "mHandThumb2Right",
    'mHandThumb3Right': "mHandThumb3Right",
    'aRight Hand': "Right Hand",
    'aR Forearm': "R Forearm",
    'aR Upper Arm': "R Upper Arm",
    'aRight Shoulder': "Right Shoulder",
    'mWingsRoot': "mWingsRoot",
    'mWing1Left': "mWing1Left",
    'mWing2Left': "mWing2Left",
    'mWing3Left': "mWing3Left",
    'mWing4Left': "mWing4Left",
    'aLeft Wing': "Left Wing",
    'mWing4FanLeft': "mWing4FanLeft",
    'mWing1Right': "mWing1Right",
    'mWing2Right': "mWing2Right",
    'mWing3Right': "mWing3Right",
    'mWing4Right': "mWing4Right",
    'aRight Wing': "Right Wing",
    'mWing4FanRight': "mWing4FanRight",
    'aChest': "Chest",
    'aSpine': "Spine",
    'aLeft Pec': "Left Pec",
    'aRight Pec': "Right Pec",
    'mHipRight': "mHipRight",
    'R_UPPER_LEG': "R_UPPER_LEG",
    'mKneeRight': "mKneeRight",
    'R_LOWER_LEG': "R_LOWER_LEG",
    'mAnkleRight': "mAnkleRight",
    'R_FOOT': "R_FOOT",
    'mFootRight': "mFootRight",
    'mToeRight': "mToeRight",
    'aRight Foot': "Right Foot",
    'aR Lower Leg': "R Lower Leg",
    'aRight Hip': "Right Hip",
    'aR Upper Leg': "R Upper Leg",
    'mHipLeft': "mHipLeft",
    'L_UPPER_LEG': "L_UPPER_LEG",
    'mKneeLeft': "mKneeLeft",
    'L_LOWER_LEG': "L_LOWER_LEG",
    'mAnkleLeft': "mAnkleLeft",
    'L_FOOT': "L_FOOT",
    'mFootLeft': "mFootLeft",
    'mToeLeft': "mToeLeft",
    'aLeft Foot': "Left Foot",
    'aL Lower Leg': "L Lower Leg",
    'aLeft Hip': "Left Hip",
    'aL Upper Leg': "L Upper Leg",
    'mTail1': "mTail1",
    'mTail2': "mTail2",
    'mTail3': "mTail3",
    'mTail4': "mTail4",
    'mTail5': "mTail5",
    'mTail6': "mTail6",
    'aTail Tip': "Tail Tip",
    'aTail Base': "Tail Base",
    'mGroin': "mGroin",
    'aGroin': "Groin",
    'mHindLimbsRoot': "mHindLimbsRoot",
    'mHindLimb1Left': "mHindLimb1Left",
    'mHindLimb2Left': "mHindLimb2Left",
    'mHindLimb3Left': "mHindLimb3Left",
    'mHindLimb4Left': "mHindLimb4Left",
    'aLeft Hind Foot': "Left Hind Foot",
    'mHindLimb1Right': "mHindLimb1Right",
    'mHindLimb2Right': "mHindLimb2Right",
    'mHindLimb3Right': "mHindLimb3Right",
    'mHindLimb4Right': "mHindLimb4Right",
    'aRight Hind Foot': "Right Hind Foot",
    'aPelvis': "Pelvis",
    'aStomach': "Stomach",
    'aAvatar Center': "Avatar Center",
    'COG': "mPelvis",
}

