
bones = {}
bones["base"] = {
    'mKneeRight', 'mAnkleRight', 'mGroin', 'mHipRight',
    'mAnkleLeft', 'mFootLeft', 'mChest', 'mElbowLeft',
    'mShoulderRight', 'mEyeLeft', 'mFootRight',
    'mCollarLeft', 'mKneeLeft', 'mSkull', 'mWristLeft',
    'mToeRight', 'mEyeRight', 'mElbowRight', 'mTorso',
    'mShoulderLeft', 'mNeck', 'mCollarRight', 'mHipLeft',
    'mHead', 'mPelvis', 'mWristRight', 'mToeLeft'
    }
bones["spine"] = {
    'mSpine1',
    'mSpine2',
    'mSpine3',
    'mSpine4',
    }
bones["wing"] = {
    'mWingsRoot',
    'mWing1Left',
    'mWing2Left',
    'mWing3Left',
    'mWing4Left',
    'mWing4FanLeft',
    'mWing1Right',
    'mWing2Right',
    'mWing3Right',
    'mWing4Right',
    'mWing4FanRight',
    }
bones["tail"] = { 
    'mTail1',
    'mTail2',
    'mTail3',
    'mTail4',
    'mTail5',
    'mTail6',
    }
bones["hind"] = {
    'mHindLimbsRoot',
    'mHindLimb1Left',
    'mHindLimb2Left',
    'mHindLimb3Left',
    'mHindLimb4Left',
    'mHindLimb1Right',
    'mHindLimb2Right',
    'mHindLimb3Right',
    'mHindLimb4Right',
    }
bones["hand"] = {
    'mHandMiddle1Left',
    'mHandMiddle2Left',
    'mHandMiddle3Left',
    'mHandIndex1Left',
    'mHandIndex2Left',
    'mHandIndex3Left',
    'mHandRing1Left',
    'mHandRing2Left',
    'mHandRing3Left',
    'mHandPinky1Left',
    'mHandPinky2Left',
    'mHandPinky3Left',
    'mHandThumb1Left',
    'mHandThumb2Left',
    'mHandThumb3Left',
    'mHandMiddle1Right',
    'mHandMiddle2Right',
    'mHandMiddle3Right',
    'mHandIndex1Right',
    'mHandIndex2Right',
    'mHandIndex3Right',
    'mHandRing1Right',
    'mHandRing2Right',
    'mHandRing3Right',
    'mHandPinky1Right',
    'mHandPinky2Right',
    'mHandPinky3Right',
    'mHandThumb1Right',
    'mHandThumb2Right',
    'mHandThumb3Right',
    }
bones["face"] = {
    'mFaceRoot',
    'mFaceEyeAltRight',
    'mFaceEyeAltLeft',
    'mFaceForeheadLeft',
    'mFaceForeheadRight',
    'mFaceEyebrowOuterLeft',
    'mFaceEyebrowCenterLeft',
    'mFaceEyebrowInnerLeft',
    'mFaceEyebrowOuterRight',
    'mFaceEyebrowCenterRight',
    'mFaceEyebrowInnerRight',
    'mFaceEyeLidUpperLeft',
    'mFaceEyeLidLowerLeft',
    'mFaceEyeLidUpperRight',
    'mFaceEyeLidLowerRight',
    'mFaceEar1Left',
    'mFaceEar2Left',
    'mFaceEar1Right',
    'mFaceEar2Right',
    'mFaceNoseLeft',
    'mFaceNoseCenter',
    'mFaceNoseRight',
    'mFaceCheekLowerLeft',
    'mFaceCheekUpperLeft',
    'mFaceCheekLowerRight',
    'mFaceCheekUpperRight',
    'mFaceJaw',
    'mFaceChin',
    'mFaceTeethLower',
    'mFaceLipLowerLeft',
    'mFaceLipLowerRight',
    'mFaceLipLowerCenter',
    'mFaceTongueBase',
    'mFaceTongueTip',
    'mFaceJawShaper',
    'mFaceForeheadCenter',
    'mFaceNoseBase',
    'mFaceTeethUpper',
    'mFaceLipUpperLeft',
    'mFaceLipUpperRight',
    'mFaceLipCornerLeft',
    'mFaceLipCornerRight',
    'mFaceLipUpperCenter',
    'mFaceEyecornerInnerLeft',
    'mFaceEyecornerInnerRight',
    'mFaceNoseBridge',
    }
bones["volume"] = {
    'PELVIS',
    'BUTT',
    'BELLY',
    'LEFT_HANDLE',
    'RIGHT_HANDLE',
    'LOWER_BACK',
    'CHEST',
    'LEFT_PEC',
    'RIGHT_PEC',
    'UPPER_BACK',
    'NECK',
    'HEAD',
    'L_CLAVICLE',
    'L_UPPER_ARM',
    'L_LOWER_ARM',
    'L_HAND',
    'R_CLAVICLE',
    'R_UPPER_ARM',
    'R_LOWER_ARM',
    'R_HAND',
    'R_UPPER_LEG',
    'R_LOWER_LEG',
    'R_FOOT',
    'L_UPPER_LEG',
    'L_LOWER_LEG',
    'L_FOOT',
    }
bones["attach"] = {
    'Alt Left Ear',
    'Alt Left Eye',
    'Alt Right Ear',
    'Alt Right Eye',
    'Chest',
    'Chin',
    'Groin',
    'Jaw',
    'L Forearm',
    'L Lower Leg',
    'L Upper Arm',
    'L Upper Leg',
    'Left Ear',
    'Left Eyeball',
    'Left Foot',
    'Left Hand',
    'Left Hind Foot',
    'Left Hip',
    'Left Pec',
    'Left Ring Finger',
    'Left Shoulder',
    'Left Wing',
    'Mouth',
    'Neck',
    'Nose',
    'Avatar Center',
    'Pelvis',
    'R Forearm',
    'R Lower Leg',
    'R Upper Arm',
    'R Upper Leg',
    'Right Ear',
    'Right Eyeball',
    'Right Foot',
    'Right Hand',
    'Right Hind Foot',
    'Right Hip',
    'Right Pec',
    'Right Ring Finger',
    'Right Shoulder',
    'Right Wing',
    'Skull',
    'Spine',
    'Stomach',
    'Tail Base',
    'Tail Tip',
    'Tongue',
    }

