bones_middle = {
    'mPelvis',
    'mSpine1',
    'mSpine2',
    'mSpine3',
    'mSpine4',
    'mTorso',
    'mChest',
    'mNeck',
    'mHead',
    'mSkull',
    'mFaceRoot',
    'mFaceJaw',
    'mFaceChin',
    'mFaceLipUpperCenter',
    'mFaceLipLowerCenter',
    'mFaceNoseCenter',
    'mFaceTongueTip',
    'mFaceJawShaper',
    'mFaceForeheadCenter',
    'mFaceNoseBase',
    'mFaceTeethUpper',
    'mFaceTeethLower',
    'mFaceTongueBase',
    'mFaceNoseBridge',
    'mWingsRoot',
    'mTail1',
    'mTail2',
    'mTail3',
    'mTail4',
    'mTail5',
    'mTail6',
    'mGroin',
    'mHindLimbsRoot',
    'NECK',
    'BELLY',
    'PELVIS',
    'CHEST',
    'HEAD',
    'BUTT',
    'UPPER_BACK',
    'LOWER_BACK',
    'Chest',
    'Chin',
    'Groin',
    'Jaw',
    'Mouth',
    'Neck',
    'Nose',
    'Pelvis',
    'Skull',
    'Spine',
    'Stomach',
    'Tail Base',
    'Tail Tip',
    'Tongue',
    }




bones_left = {
    'mEyeLeft': "mEyeRight",
    'mFaceEyeAltLeft': "mFaceEyeAltRight",
    'mFaceForeheadLeft': "mFaceForeheadRight",
    'mFaceEyebrowOuterLeft': "mFaceEyebrowOuterRight",
    'mFaceEyebrowCenterLeft': "mFaceEyebrowCenterRight",
    'mFaceEyebrowInnerLeft': "mFaceEyebrowInnerRight",
    'mFaceEyeLidUpperLeft': "mFaceEyeLidUpperRight",
    'mFaceEyeLidLowerLeft': "mFaceEyeLidLowerRight",
    'mFaceEar1Left': "mFaceEar1Right",
    'mFaceEar2Left': "mFaceEar2Right",
    'mFaceNoseLeft': "mFaceNoseRight",
    'mFaceCheekLowerLeft': "mFaceCheekLowerRight",
    'mFaceCheekUpperLeft': "mFaceCheekUpperRight",
    'mFaceLipLowerLeft': "mFaceLipLowerRight",
    'mFaceLipUpperLeft': "mFaceLipUpperRight",
    'mFaceLipCornerLeft': "mFaceLipCornerRight",
    'mFaceEyecornerInnerLeft': "mFaceEyecornerInnerRight",
    'mCollarLeft': "mCollarRight",
    'mShoulderLeft': "mShoulderRight",
    'mElbowLeft': "mElbowRight",
    'mWristLeft': "mWristRight",
    'mHandMiddle1Left': "mHandMiddle1Right",
    'mHandMiddle2Left': "mHandMiddle2Right",
    'mHandMiddle3Left': "mHandMiddle3Right",
    'mHandIndex1Left': "mHandIndex1Right",
    'mHandIndex2Left': "mHandIndex2Right",
    'mHandIndex3Left': "mHandIndex3Right",
    'mHandRing1Left': "mHandRing1Right",
    'mHandRing2Left': "mHandRing2Right",
    'mHandRing3Left': "mHandRing3Right",
    'mHandPinky1Left': "mHandPinky1Right",
    'mHandPinky2Left': "mHandPinky2Right",
    'mHandPinky3Left': "mHandPinky3Right",
    'mHandThumb1Left': "mHandThumb1Right",
    'mHandThumb2Left': "mHandThumb2Right",
    'mHandThumb3Left': "mHandThumb3Right",
    'mWing1Left': "mWing1Right",
    'mWing2Left': "mWing2Right",
    'mWing3Left': "mWing3Right",
    'mWing4Left': "mWing4Right",
    'mWing4FanLeft': "mWing4FanRight",
    'mHipLeft': "mHipRight",
    'mKneeLeft': "mKneeRight",
    'mAnkleLeft': "mAnkleRight",
    'mFootLeft': "mFootRight",
    'mToeLeft': "mToeRight",
    'mHindLimb1Left': "mHindLimb1Right",
    'mHindLimb2Left': "mHindLimb2Right",
    'mHindLimb3Left': "mHindLimb3Right",
    'mHindLimb4Left': "mHindLimb4Right",
    'LEFT_PEC': "RIGHT_PEC",
    'L_CLAVICLE': "R_CLAVICLE",
    'L_UPPER_ARM': "R_UPPER_ARM",
    'L_LOWER_ARM': "R_LOWER_ARM",
    'LEFT_HANDLE': "RIGHT_HANDLE",
    'L_UPPER_LEG': "R_UPPER_LEG",
    'L_LOWER_LEG': "R_LOWER_LEG",
    'L_HAND': "R_HAND",
    'L_FOOT': "R_FOOT",
    'Alt Left Ear': "Alt Right Ear",
    'Alt Left Eye': "Alt Right Eye",
    'L Forearm': "R Forearm",
    'L Lower Leg': "R Lower Leg",
    'L Upper Arm': "R Upper Arm",
    'L Upper Leg': "R Upper Leg",
    'Left Ear': "Right Ear",
    'Left Eyeball': "Right Eyeball",
    'Left Foot': "Right Foot",
    'Left Hand': "Right Hand",
    'Left Hind Foot': "Right Hind Foot",
    'Left Hip': "Right Hip",
    'Left Pec': "Right Pec",
    'Left Ring Finger': "Right Ring Finger",
    'Left Shoulder': "Right Shoulder",
    'Left Wing': "Right Wing",
    'Alt Left Ear': "Alt Right Ear",
    'Alt Left Eye': "Alt Right Eye",
    'L Forearm': "R Forearm",
    'L Lower Leg': "R Lower Leg",
    'L Upper Arm': "R Upper Arm",
    'L Upper Leg': "R Upper Leg",
    'Left Ear': "Right Ear",
    'Left Eyeball': "Right Eyeball",
    'Left Foot': "Right Foot",
    'Left Hand': "Right Hand",
    'Left Hind Foot': "Right Hind Foot",
    'Left Hip': "Right Hip",
    'Left Pec': "Right Pec",
    'Left Ring Finger': "Right Ring Finger",
    'Left Shoulder': "Right Shoulder",
    'Left Wing': "Right Wing",
    }

bones_right = {
    'mEyeRight': "mEyeLeft",
    'mFaceEyeAltRight': "mFaceEyeAltLeft",
    'mFaceForeheadRight': "mFaceForeheadLeft",
    'mFaceEyebrowOuterRight': "mFaceEyebrowOuterLeft",
    'mFaceEyebrowCenterRight': "mFaceEyebrowCenterLeft",
    'mFaceEyebrowInnerRight': "mFaceEyebrowInnerLeft",
    'mFaceEyeLidUpperRight': "mFaceEyeLidUpperLeft",
    'mFaceEyeLidLowerRight': "mFaceEyeLidLowerLeft",
    'mFaceEar1Right': "mFaceEar1Left",
    'mFaceEar2Right': "mFaceEar2Left",
    'mFaceNoseRight': "mFaceNoseLeft",
    'mFaceCheekLowerRight': "mFaceCheekLowerLeft",
    'mFaceCheekUpperRight': "mFaceCheekUpperLeft",
    'mFaceLipLowerRight': "mFaceLipLowerLeft",
    'mFaceLipUpperRight': "mFaceLipUpperLeft",
    'mFaceLipCornerRight': "mFaceLipCornerLeft",
    'mFaceEyecornerInnerRight': "mFaceEyecornerInnerLeft",
    'mCollarRight': "mCollarLeft",
    'mShoulderRight': "mShoulderLeft",
    'mElbowRight': "mElbowLeft",
    'mWristRight': "mWristLeft",
    'mHandMiddle1Right': "mHandMiddle1Left",
    'mHandMiddle2Right': "mHandMiddle2Left",
    'mHandMiddle3Right': "mHandMiddle3Left",
    'mHandIndex1Right': "mHandIndex1Left",
    'mHandIndex2Right': "mHandIndex2Left",
    'mHandIndex3Right': "mHandIndex3Left",
    'mHandRing1Right': "mHandRing1Left",
    'mHandRing2Right': "mHandRing2Left",
    'mHandRing3Right': "mHandRing3Left",
    'mHandPinky1Right': "mHandPinky1Left",
    'mHandPinky2Right': "mHandPinky2Left",
    'mHandPinky3Right': "mHandPinky3Left",
    'mHandThumb1Right': "mHandThumb1Left",
    'mHandThumb2Right': "mHandThumb2Left",
    'mHandThumb3Right': "mHandThumb3Left",
    'mWing1Right': "mWing1Left",
    'mWing2Right': "mWing2Left",
    'mWing3Right': "mWing3Left",
    'mWing4Right': "mWing4Left",
    'mWing4FanRight': "mWing4FanLeft",
    'mHipRight': "mHipLeft",
    'mKneeRight': "mKneeLeft",
    'mAnkleRight': "mAnkleLeft",
    'mFootRight': "mFootLeft",
    'mToeRight': "mToeLeft",
    'mHindLimb1Right': "mHindLimb1Left",
    'mHindLimb2Right': "mHindLimb2Left",
    'mHindLimb3Right': "mHindLimb3Left",
    'mHindLimb4Right': "mHindLimb4Left",
    'RIGHT_PEC': "LEFT_PEC",
    'R_CLAVICLE': "L_CLAVICLE",
    'R_UPPER_ARM': "L_UPPER_ARM",
    'R_LOWER_ARM': "L_LOWER_ARM",
    'RIGHT_HANDLE': "LEFT_HANDLE",
    'R_UPPER_LEG': "L_UPPER_LEG",
    'R_LOWER_LEG': "L_LOWER_LEG",
    'R_HAND': "L_HAND",
    'R_FOOT': "L_FOOT",
    'Alt Right Ear': "Alt Left Ear",
    'Alt Right Eye': "Alt Left Eye",
    'R Forearm': "L Forearm",
    'R Lower Leg': "L Lower Leg",
    'R Upper Arm': "L Upper Arm",
    'R Upper Leg': "L Upper Leg",
    'Right Ear': "Left Ear",
    'Right Eyeball': "Left Eyeball",
    'Right Foot': "Left Foot",
    'Right Hand': "Left Hand",
    'Right Hind Foot': "Left Hind Foot",
    'Right Hip': "Left Hip",
    'Right Pec': "Left Pec",
    'Right Ring Finger': "Left Ring Finger",
    'Right Shoulder': "Left Shoulder",
    'Right Wing': "Left Wing",
    'Alt Right Ear': "Alt Left Ear",
    'Alt Right Eye': "Alt Left Eye",
    'R Forearm': "L Forearm",
    'R Lower Leg': "L Lower Leg",
    'R Upper Arm': "L Upper Arm",
    'R Upper Leg': "L Upper Leg",
    'Right Ear': "Left Ear",
    'Right Eyeball': "Left Eyeball",
    'Right Foot': "Left Foot",
    'Right Hand': "Left Hand",
    'Right Hind Foot': "Left Hind Foot",
    'Right Hip': "Left Hip",
    'Right Pec': "Left Pec",
    'Right Ring Finger': "Left Ring Finger",
    'Right Shoulder': "Left Shoulder",
    'Right Wing': "Left Wing",
    }
both_sides = {
    'mEyeLeft': "mEyeRight",
    'mEyeRight': "mEyeLeft",
    'mFaceEyeAltLeft': "mFaceEyeAltRight",
    'mFaceEyeAltRight': "mFaceEyeAltLeft",
    'mFaceForeheadLeft': "mFaceForeheadRight",
    'mFaceForeheadRight': "mFaceForeheadLeft",
    'mFaceEyebrowOuterLeft': "mFaceEyebrowOuterRight",
    'mFaceEyebrowOuterRight': "mFaceEyebrowOuterLeft",
    'mFaceEyebrowCenterLeft': "mFaceEyebrowCenterRight",
    'mFaceEyebrowCenterRight': "mFaceEyebrowCenterLeft",
    'mFaceEyebrowInnerLeft': "mFaceEyebrowInnerRight",
    'mFaceEyebrowInnerRight': "mFaceEyebrowInnerLeft",
    'mFaceEyeLidUpperLeft': "mFaceEyeLidUpperRight",
    'mFaceEyeLidUpperRight': "mFaceEyeLidUpperLeft",
    'mFaceEyeLidLowerLeft': "mFaceEyeLidLowerRight",
    'mFaceEyeLidLowerRight': "mFaceEyeLidLowerLeft",
    'mFaceEar1Left': "mFaceEar1Right",
    'mFaceEar1Right': "mFaceEar1Left",
    'mFaceEar2Left': "mFaceEar2Right",
    'mFaceEar2Right': "mFaceEar2Left",
    'mFaceNoseLeft': "mFaceNoseRight",
    'mFaceNoseRight': "mFaceNoseLeft",
    'mFaceCheekLowerLeft': "mFaceCheekLowerRight",
    'mFaceCheekLowerRight': "mFaceCheekLowerLeft",
    'mFaceCheekUpperLeft': "mFaceCheekUpperRight",
    'mFaceCheekUpperRight': "mFaceCheekUpperLeft",
    'mFaceLipLowerLeft': "mFaceLipLowerRight",
    'mFaceLipLowerRight': "mFaceLipLowerLeft",
    'mFaceLipUpperLeft': "mFaceLipUpperRight",
    'mFaceLipUpperRight': "mFaceLipUpperLeft",
    'mFaceLipCornerLeft': "mFaceLipCornerRight",
    'mFaceLipCornerRight': "mFaceLipCornerLeft",
    'mFaceEyecornerInnerLeft': "mFaceEyecornerInnerRight",
    'mFaceEyecornerInnerRight': "mFaceEyecornerInnerLeft",
    'mCollarLeft': "mCollarRight",
    'mCollarRight': "mCollarLeft",
    'mShoulderLeft': "mShoulderRight",
    'mShoulderRight': "mShoulderLeft",
    'mElbowLeft': "mElbowRight",
    'mElbowRight': "mElbowLeft",
    'mWristLeft': "mWristRight",
    'mWristRight': "mWristLeft",
    'mHandMiddle1Left': "mHandMiddle1Right",
    'mHandMiddle1Right': "mHandMiddle1Left",
    'mHandMiddle2Left': "mHandMiddle2Right",
    'mHandMiddle2Right': "mHandMiddle2Left",
    'mHandMiddle3Left': "mHandMiddle3Right",
    'mHandMiddle3Right': "mHandMiddle3Left",
    'mHandIndex1Left': "mHandIndex1Right",
    'mHandIndex1Right': "mHandIndex1Left",
    'mHandIndex2Left': "mHandIndex2Right",
    'mHandIndex2Right': "mHandIndex2Left",
    'mHandIndex3Left': "mHandIndex3Right",
    'mHandIndex3Right': "mHandIndex3Left",
    'mHandRing1Left': "mHandRing1Right",
    'mHandRing1Right': "mHandRing1Left",
    'mHandRing2Left': "mHandRing2Right",
    'mHandRing2Right': "mHandRing2Left",
    'mHandRing3Left': "mHandRing3Right",
    'mHandRing3Right': "mHandRing3Left",
    'mHandPinky1Left': "mHandPinky1Right",
    'mHandPinky1Right': "mHandPinky1Left",
    'mHandPinky2Left': "mHandPinky2Right",
    'mHandPinky2Right': "mHandPinky2Left",
    'mHandPinky3Left': "mHandPinky3Right",
    'mHandPinky3Right': "mHandPinky3Left",
    'mHandThumb1Left': "mHandThumb1Right",
    'mHandThumb1Right': "mHandThumb1Left",
    'mHandThumb2Left': "mHandThumb2Right",
    'mHandThumb2Right': "mHandThumb2Left",
    'mHandThumb3Left': "mHandThumb3Right",
    'mHandThumb3Right': "mHandThumb3Left",
    'mWing1Left': "mWing1Right",
    'mWing1Right': "mWing1Left",
    'mWing2Left': "mWing2Right",
    'mWing2Right': "mWing2Left",
    'mWing3Left': "mWing3Right",
    'mWing3Right': "mWing3Left",
    'mWing4Left': "mWing4Right",
    'mWing4Right': "mWing4Left",
    'mWing4FanLeft': "mWing4FanRight",
    'mWing4FanRight': "mWing4FanLeft",
    'mHipLeft': "mHipRight",
    'mHipRight': "mHipLeft",
    'mKneeLeft': "mKneeRight",
    'mKneeRight': "mKneeLeft",
    'mAnkleLeft': "mAnkleRight",
    'mAnkleRight': "mAnkleLeft",
    'mFootLeft': "mFootRight",
    'mFootRight': "mFootLeft",
    'mToeLeft': "mToeRight",
    'mToeRight': "mToeLeft",
    'mHindLimb1Left': "mHindLimb1Right",
    'mHindLimb1Right': "mHindLimb1Left",
    'mHindLimb2Left': "mHindLimb2Right",
    'mHindLimb2Right': "mHindLimb2Left",
    'mHindLimb3Left': "mHindLimb3Right",
    'mHindLimb3Right': "mHindLimb3Left",
    'mHindLimb4Left': "mHindLimb4Right",
    'mHindLimb4Right': "mHindLimb4Left",
    'LEFT_PEC': "RIGHT_PEC",
    'RIGHT_PEC': "LEFT_PEC",
    'L_CLAVICLE': "R_CLAVICLE",
    'R_CLAVICLE': "L_CLAVICLE",
    'L_UPPER_ARM': "R_UPPER_ARM",
    'R_UPPER_ARM': "L_UPPER_ARM",
    'L_LOWER_ARM': "R_LOWER_ARM",
    'R_LOWER_ARM': "L_LOWER_ARM",
    'LEFT_HANDLE': "RIGHT_HANDLE",
    'RIGHT_HANDLE': "LEFT_HANDLE",
    'L_UPPER_LEG': "R_UPPER_LEG",
    'R_UPPER_LEG': "L_UPPER_LEG",
    'L_LOWER_LEG': "R_LOWER_LEG",
    'R_LOWER_LEG': "L_LOWER_LEG",
    'L_HAND': "R_HAND",
    'R_HAND': "L_HAND",
    'L_FOOT': "R_FOOT",
    'R_FOOT': "L_FOOT",
    'Alt Left Ear': "Alt Right Ear",
    'Alt Right Ear': "Alt Left Ear",
    'Alt Left Eye': "Alt Right Eye",
    'Alt Right Eye': "Alt Left Eye",
    'L Forearm': "R Forearm",
    'R Forearm': "L Forearm",
    'L Lower Leg': "R Lower Leg",
    'R Lower Leg': "L Lower Leg",
    'L Upper Arm': "R Upper Arm",
    'R Upper Arm': "L Upper Arm",
    'L Upper Leg': "R Upper Leg",
    'R Upper Leg': "L Upper Leg",
    'Left Ear': "Right Ear",
    'Right Ear': "Left Ear",
    'Left Eyeball': "Right Eyeball",
    'Right Eyeball': "Left Eyeball",
    'Left Foot': "Right Foot",
    'Right Foot': "Left Foot",
    'Left Hand': "Right Hand",
    'Right Hand': "Left Hand",
    'Left Hind Foot': "Right Hind Foot",
    'Right Hind Foot': "Left Hind Foot",
    'Left Hip': "Right Hip",
    'Right Hip': "Left Hip",
    'Left Pec': "Right Pec",
    'Right Pec': "Left Pec",
    'Left Ring Finger': "Right Ring Finger",
    'Right Ring Finger': "Left Ring Finger",
    'Left Shoulder': "Right Shoulder",
    'Right Shoulder': "Left Shoulder",
    'Left Wing': "Right Wing",
    'Right Wing': "Left Wing",
}
